server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    properties:
      database-platform: com.uns.ac.rs.userservice.configuration.ImprovedMySQLDialect
      hibernate:
        dialect: com.uns.ac.rs.userservice.configuration.ImprovedMySQLDialect
        #storage_engine: innodb
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    hibernate:
      naming_stratgey: org.hibernate.cfg.EJB3NamingStrategy
      #ddl-auto: create
      #ddl-auto: update
      ddl-auto: create-drop
    show_sql: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/users?allowPublicKeyRetrieval=true&useSSL=false
#    initialization-mode: never
    initialization-mode: always